package com.hadyandev.charalist;

import java.util.ArrayList;

public class CharacterData {
    public static String[][] data = new String[][]{
            {"Light Yagami", "Death Note", "Light Yagami (夜神月, Yagami Raito) is the main protagonist of the Death Note series. After discovering the Death Note, he decides to use it to rid the world of criminals. His killings are eventually labelled by people of Japan as the work of \"Kira.\"", "\"If we catch Kira, he is evil. If he wins and rules the world, then he is justice.\"", "https://vignette.wikia.nocookie.net/deathnote/images/9/9c/Light_yagami.jpg/revision/latest?c=20110801092518"},
            {"L", "Death Note", "L (エル, Eru) is a world-renowned detective who takes on the challenge of catching the mass murderer known as Kira. In his investigation, L becomes suspicious of Light Yagami and makes it his goal to prove that Light is Kira.", "\"Kira is childish, and he hates losing. You guessed it, I'm also childish and hate losing. \"", "https://vignette.wikia.nocookie.net/deathnote/images/7/78/--p.jpg/revision/latest?cb=20120329040427"},
            {"Near", "Death Note", "Near (ニア, Nia) is the younger of L's two successors, raised in Wammy's House—Watari's orphanage for gifted children in Winchester, England. After L\'s death, Near begins his investigation of the Kira case, gathering evidence over a period of four years. Near takes his findings to the President of the United States and reveals himself to be the true successor of L. Soon after, Near becomes the head of the Special Provision for Kira and continues the hunt for Kira. After making contact with \"L\" (Light Yagami), Near begins to suspect that the current L is also Kira.", "\"Nobody can tell what is right and what is wrong, what is righteous and what is evil. Even if there is a god, and I had His teachings before me, I would think it through, and decide if that was right or wrong myself.\"", "https://vignette.wikia.nocookie.net/deathnote/images/a/a4/Near4fv3.jpg/revision/latest?cb=20120515212024"},
            {"Mello", "Death Note", "Mello (メロ, Mero) is the older of L's two successors, raised at Wammy's House—Watari's orphanage for gifted children in Winchester, England. When Roger decides that Mello should work with Near to capture Kira, he refuses, citing an inability to work with somebody to whom he is considered \"second.\" He leaves the orphanage soon after, stating \"I\'ll find my own way,\" and he eventually seeks help from the Mafia.", "\"It's not just the notebook I'm after. I wanna eliminate my competition. I will be the best. I don't care what it takes. I'll beat Near by any means necessary.\"", "https://vignette.wikia.nocookie.net/deathnote/images/e/e1/Mello-01.jpg/revision/latest?cb=20110828082656"},
            {"Lelouch Vi Britania", "Code Geass", "Lelouch vi Britannia (ルルーシュ・ヴィ・ブリタニア, Rurūshu vui Buritania) was the protagonist of Code Geass: Lelouch of the Rebellion and Code Geass: Lelouch of the Rebellion R2, 17 years old (18 at R2). After he was exiled he used the alias, Lelouch Lamperouge (ルルーシュ・ランペルージ, Rurūshu Ranperūji). He was the Eleventh Prince of the Holy Britannian Empire and the son of the 98th Emperor of Britannia, Charles zi Britannia. He was also the leader of the Black Knights and the real identity of Zero.", "\"If the king does not lead, how can he expect his subordinates to follow?\"", "https://vignette.wikia.nocookie.net/codegeass/images/f/f1/Lelouch12.jpg/revision/latest?cb=20120728070011"},
            {"Suzaku Kururugi", "Code Geass", "Suzaku Kururugi (枢木 スザク / くるるぎすざく), Kururugi Suzaku), 17 years old (18 at R2), is the deuteragonist of the Sunrise anime series Code Geass: Lelouch of the Rebellion, and one of the protagonists of Code Geass: Lancelot & Guren.", "\"Just want you to ask yourself: when you gain results the wrong way, what are you left with in the end? Only dark regret and a deep emptiness that have nowhere to go.\"", "https://vignette.wikia.nocookie.net/codegeass/images/7/7d/Suzaku-brittania-knight.jpg/revision/latest?cb=20111219101440"},
            {"Schneizel el Britannia", "Code Geass", "Schneizel el Britannia (シュナイゼル エル ブリタニア, Shunaizeru eru Buritania), 27 years old (28 at R2), is the Second Prince of the Britannian Imperial Family and the Prime Minister of the Holy Britannian Empire. He is a strategist on par with Lelouch, and the only person Lelouch was unable to beat in chess as a child. Charismatic and manipulative, cunning and ruthless, Schneizel is widely regarded as Lelouch's greatest adversary, including Lelouch himself, and the Prime Minister serves as one of the primary antagonists of the series, particularly in Season 2.", "\"Even civilians who have rejected war depend on the police, don't they? Everyone knows, don't they ... that people are driven by their own desires. The lust that dwells within the soul of man cannot be denied. So why win hearts and minds or tout some shining ideology? Why not bring peace to the world with a system and power?\"", "https://vignette.wikia.nocookie.net/codegeass/images/3/32/Schneizel_el_britania.jpg/revision/latest?cb=20110109084341"},
            {"Edward Elric", "Fullmetal Alchemist Brotherhood", "Edward Elric (エドワード・エルリック Edowādo Erurikku?), also known as Ed or the Fullmetal Alchemist (鋼の錬金術師, Hagane no Renkinjutsushi?), is the titular protagonist of the Fullmetal Alchemist series.\n" +
                    "\n" +
                    "After losing his right arm and left leg due to a failed Human Transmutation attempt, Ed became the youngest State Alchemist in history by achieving his certification at age twelve. Three years later, Ed has become fully engrossed in his search for the legendary Philosopher's Stone, an item with which he hopes to restore his younger brother Alphonse Elric - whose whole body had been lost in the aftermath of the human transmutation.", "\"Whether it be an arm, or a leg, or even my heart you can take it!! So give him back... HE'S MY LITTLE BROTHER AND HE'S ALL I HAVE LEFT!!!\"", "https://vignette.wikia.nocookie.net/fma/images/d/d3/Avatar_edward.png/revision/latest?cb=20180406214254"},
            {"Roy Mustang", "Fullmetal Alchemist Brotherhood", "Roy Mustang (ロイ・マスタング Roi Masutangu?), also known as the Flame Alchemist (焔の錬金術師 Honō no Renkinjutsushi?), is the tritagonist of the Fullmetal Alchemist series. He is a State Alchemist and officer in the Amestrian State Military. A hero of the Ishval Civil War and Edward Elric’s superior officer, Colonel Mustang is a remarkably capable commander who plans to become the next Führer of Amestris.", "\"If you believe the possibility exists, then you should do whatever it takes.\"", "https://vignette.wikia.nocookie.net/fma/images/b/bb/Avatar_roy.png/revision/latest?cb=20171026195109"},
            {"Alphonse Elric", "Fullmetal Alchemist Brotherhood", "Alphonse Elric (アルフォンス・エルリック Arufonsu Erurikku?), also known as Al, is the deuteragonist of the Fullmetal Alchemist series. He is the younger brother of the Fullmetal Alchemist Edward Elric. Al is also a victim of the failed Human Transmutation experiment in which Ed lost his right arm and left leg. Having had his entire physical being taken away from him in the aftermath of the tragedy, Alphonse exists solely as a soul alchemically bound to a large suit of steel armor. Now, Al travels with his brother in search of a legendary Philosopher's Stone, an item with the power to restore their bodies to normal.", "\"I can't take all the nights by myself! It's too lonely... and that's why I have to get back to normal.\"", "https://vignette.wikia.nocookie.net/fma/images/5/51/Avatar_alphonse.png/revision/latest?cb=20160722004325"},
            {"Winry Rockbell", "Fullmetal Alchemist Brotherhood", "Winry Rockbell (ウィンリィ・ロックベル, Winrī Rokkuberu) is a main supporting character of the Fullmetal Alchemist series. She is Edward Elric and Alphonse Elric’s close childhood friend of ever since their young life in Resembool and is almost like a sister to the two and essentially their only family. An amateur surgeon and mechanical repair specialist/enthusiast, Winry is Edward's rear line support as his personal automail engineer and mechanic, making sure his prosthetic right arm and left leg are always in good working order. Additionally, she provides a great deal of emotional support for the pair and plays the role of Edward's love interest.", "\"So that's why you're a thief? If you're so grateful, then you should clean up your act and stop picking pockets! Mr. Dominic gave you these legs out of a selfless act of good will!\"", "https://vignette.wikia.nocookie.net/fma/images/9/90/Avatar_winry.png/revision/latest?cb=20180407203943"},
            {"Ling Yao", "Fullmetal Alchemist Brotherhood", "Ling Yao (リン・ヤオ, Rin Yao), also spelled as Lin Yao, is the twelfth crown prince of the eastern nation of Xing and the liege of the Yao clan. Seeking a way to ensure his path to the throne amidst deadly inter-house competition, Ling has ventured from Xing to Amestris in order to divine the secret of immortality - the Philosopher's Stone.", "\"A king exists for his people. Without his people, there can be no king.\"", "https://vignette.wikia.nocookie.net/fma/images/c/ce/Ling_Yao.png/revision/latest?cb=20140527123845&path-prefix=es"},
            {"Riza Hawkeye", "Fullmetal Alchemist Brotherhood", "Lieutenant Riza Hawkeye (リザ・ホークアイ, Riza Hōkuai) is an officer in the Amestrian State Military as well as the personal adjutant and bodyguard of Colonel Roy Mustang. A sharpshooter and firearms specialist, Lt. Hawkeye is an invaluable asset to the Colonel both in office and on the battlefield and serves as his closest and most supportive subordinate.", "\"If the ways of this world are based on equivalent exchange, as alchemy says, then in order to allow for a new generation to enjoy good fortune, then the price that we must pay is to carry the bodies of the dead across a river of blood.\"", "https://vignette.wikia.nocookie.net/fma/images/2/26/Riza-profile.png/revision/latest?cb=20140306200414"},
            {"King Bradley", "Fullmetal Alchemist Brotherhood", "King Bradley (キング・ブラッドレイ Kingu Buraddorei?) is one of the primary antagonists in the Fullmetal Alchemist series, being that he is one of the seven Homunculi. Bradley was also the original Führer (大総統 Daisōtō?) of Amestris. In the manga series and the 2009 anime reboot, he was known as Wrath (ラース Rāsu?), the final homunculus created by Father, but was changed in the 2003 anime to Pride (プライド Puraido?), created by the ancient alchemist Dante. In both series, Bradley is the leader of Amestris and is seen to have almost inhuman swordsmanship. However, in the manga and 2009 anime series, he is an important character being that Amestris was created for the sole purpose of exacting Father's plan to become the ultimate being. As Führer, Bradley is the respected Commander-in-Chief of the State Military, even though his political standpoints are often questioned in certain instances such as the Ishval Civil War, which was only one of many insurrections focused on creating a massive Philosopher's Stone for Father.", "\"Why must everyone make such a fuss over the death of a single soldier? The moment a soldier dons his uniform, he accepts the reality that he might be buried in it.\"", "https://vignette.wikia.nocookie.net/fma/images/0/0b/KingBradley1080p.png/revision/latest?cb=20161230194652"},
            {"Van Hohenheim", "Fullmetal Alchemist Brotherhood", "Van Hohenheim—also known in the 2003 anime series as Hohenheim of Light (光のホーエンハイム, Hikari no Hōenhaimu)—is a deceptively ancient and extremely powerful Alchemist as well as the estranged father of Edward and Alphonse Elric. Despite disappearing suddenly during their infancy, Hohenheim returns during the course of the series in order to right the wrongs of his mysterious past.", "\"I thought living forever was nothing but exhausting. But since I met you and our sons, for the first time I felt glad to be alive. It was a full life.\"", "https://vignette.wikia.nocookie.net/fma/images/e/ef/Avatar_hohenheim.png/revision/latest?cb=20180406215022"}
    };

    public static ArrayList<Character> getListData(){
        Character character = null;
        ArrayList<Character> list = new ArrayList<>();
        for (String[] aData : data) {
            character = new Character();
            character.setName(aData[0]);
            character.setAnime(aData[1]);
            character.setDescription(aData[2]);
            character.setQuote(aData[3]);
            character.setPhoto(aData[4]);

            list.add(character);
        }

        return list;
    }
}
